### PR TITLE
Docs: Add documentation for project deprecation

### PR DESCRIPTION
**Pull request by leojonathanoh**

### CODE REVIEW

**Comment by joeltimothyoh** [comment]
I'm keeping it as it has been. The README files for the modules I developed are based off the same template. I'd be confusing for the reader to simplify the docs to such an extent in the upcoming release just as the module is being deprecated.

**Comment by leojonathanoh** [comment]
let's go ahead then, and deprecate it. Then we can decide whether the docs in #20 are a bit too much.

**Comment by joeltimothyoh** [comment]
> let's go ahead then, and deprecate it. Then we can decide whether the docs in #20 are a bit too much.

This isn't a concern since the module isn't even recommended for use anymore.

**Comment by leojonathanoh** [comment]
most of #20 is really adding a snippet that is related to a manner of how to use a declarative way of managing links rather than how to use the module itself. i'm still finding most of the readme a bit too verbose for my liking.

**Comment by joeltimothyoh** [comment]
It's about to be archived.

**Comment by leojonathanoh** [comment]
> It's about to be archived.

yes, so it should be straightforward about what the module really achieves and all other documentation are really a detraction.

**Comment by leojonathanoh** [comment]
to me, just because a lot of work has been done that turned out to not achieve much in the end, doesn't mean all of its complexity should also be included to make the work appear like it means to do more than it really does. So i would cut out all the distraction and be upfront about the uselessness of the work to do the new user a favor.

**Comment by joeltimothyoh** [comment]
> yes, so it should be straightforward about what the module really achieves and all other documentation are really a detraction.

The docs and sample files demonstrate a scalable way of managing links with the module which was in part the reason for its creation.

**Comment by leojonathanoh** [comment]
if i were a new user, it would be nice to know why a project is deprecated, and the more upfront the author the project's purposelessness, the more i would appreciate the work, because sometimes even a small problem takes work that appeared to go nowhere, to be identified. this MR deserves another thought than marked `wontfix`.

**Comment by joeltimothyoh** [comment]
I did say to not to open another MR to #20. It isn’t as though the changes here better clarifies the reason for the module’s deprecation. #20 however recommends against use of the module while preserving the intelligent use of link definition files and link management workflow which again relates to the general design and purpose of the project – link management, similar to that of [scheduledtask management](https://github.com/theohbrothers/ScheduledTaskManagement). @leojonathanoh

**Comment by leojonathanoh** [comment]
What is apparent now is that the module does only one thing more than `New-Item`, and that the very same IaC concepts now apply to `New-Item` .

The main concern here is what was the main agenda of this repo:
1. Create a new helper Cmdlet. 
2. Demonstate usage of declarative IaC for powershell native cmdlets.

I believe that we agree that `1.` is the main agenda. I don't think it's `2.`, because if it was, the repo would have be created solely for demonstration of using declarative IaC for `New-item` itself. But would it be so?

Hence, if one deprecated a repo, what the deprecation should be concerned about should be about `1.` and not `2.` at all. That is, leave out all IaC demos, and go straight for the explanation why the agenda was not needed. That's what i think this PR is doing.

**Pull request closed without merging**
