### PR TITLE
Docs: Improve documentation on module

### PR DESCRIPTION
**Pull request by joeltimothyoh**

### CODE REVIEW

**Comment by leojonathanoh** [comment]
is it necessary to add so much info? Most users should know how to use the cmdlet. Unless this is for untechnical users, who probably won't even need to be managing such links?

**Comment by joeltimothyoh** [comment]
@leojonathanoh It's a based upon the same template some of the other PS projects use. It's useful trust me based on how confusing it is to manage PS modules. Extra benefit for when developing or using the module as a submodule.

**Comment by joeltimothyoh** [comment]
Anything to modify? @leojonathanoh

**Comment by leojonathanoh** [comment]
@joeltimothyoh nothing, since ready to archive

**Comment by joeltimothyoh** [comment]
lgtm

**Pull request merged**
