### PR TITLE
Build: Add azure-pipelines.yml

### PR DESCRIPTION
**Pull request by joeltimothyoh**

### CODE REVIEW

**Comment by joeltimothyoh** [comment]
It isn't clear why:

* the `ubuntu` container jobs are failing to import the module: https://dev.azure.com/theohbrothers/ItemLinkManagement/_build/results?buildId=308&view=logs&j=6faa9437-b161-58c7-e840-ecbc27faf593&t=84ddec43-f767-55cc-70a4-c66fc6a0b46e&l=71
* the `alpine` containers aren't running: https://dev.azure.com/theohbrothers/ItemLinkManagement/_build/results?buildId=308&view=logs&j=be980581-d0a2-5aa3-6dea-336a70b8fa9d&t=cfb90345-39d1-44b1-962d-4de377fbb4b1&l=49

**Comment by leojonathanoh** [comment]
no idea but id recommend to use github workflows like the other projects.

**Comment by joeltimothyoh** [comment]
`bash` is required: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops#linux-based-containers

**Comment by leojonathanoh** [comment]
strange requirement. this means azp cannot be used for containers without bash.

**Comment by leojonathanoh** [comment]
actually looking at the linux VM logs, i think there path should be `./src/<MODULE>/public`. Theres a bug in that line.

**Comment by joeltimothyoh** [comment]
> actually looking at the linux VM logs, i think the path should be ./src/<MODULE>/public. Theres a bug in that line.

Based on the `alpine` job link in https://github.com/theohbrothers/ItemLinkManagement/pull/2#issuecomment-890534075 it *doesn't* look incorrect:

```powershell
Get-ChildItem : Cannot find path '/home/vsts/work/1/s/src/ItemLinkManagement/Public' because it does not exist.`
```

**Comment by leojonathanoh** [comment]
Generate module manifest manually first, and remove Export-Modulemanifest since no longer importing .psm1 directly

**Comment by leojonathanoh** [comment]
@joeltimothyoh i think i'ts because of the usage of `$script:MODULE`https://github.com/theohbrothers/ItemLinkManagement/blob/master/src/ItemLinkManagement/ItemLinkManagement.psm1#L8-L10, where the variable now runs under the `PSModulePublisher` script context.
https://github.com/theohbrothers/PSModulePublisher/blob/cc322a9db9e9e57870f4a43a2348c49ff23f7785/templates/azure-pipelines/steps/pwsh/run-build.yml#L6

Remove `$script` scope.

**Comment by joeltimothyoh** [comment]
Nope. I found the cause: https://github.com/theohbrothers/ItemLinkManagement/pull/2/commits/8ee5c6410c2520a49867625f8e8a566a3f94bbf6

**Comment by leojonathanoh** [comment]
@joeltimothyoh ok, the azp abstraction makes it dififcult to debug and find the cause, not sure if it's worthwhile to use it

**Comment by leojonathanoh** [comment]
@joeltimothyoh btw if using `.psd1`  then the module should not contain Export-Modulemember in the `.psm1`. And `psd1` should be committed alongside `.psm1`.

**Comment by joeltimothyoh** [comment]
> @joeltimothyoh btw if using .psd1 then the module should not contain Export-Modulemember in the .psm1. And psd1 should be committed alongside .psm1.

I'm not clear since they are different. There's the choice of importing the module via the manifest or straight from `.psm1`. Given my preference for using PowerShell modules as git submodules if possible, both choices should be available. @leojonathanoh

**Comment by leojonathanoh** [comment]
@joeltimothyoh if one is going to be publishing the module on PSGallery and `.psd1` is mandatory, then one would have to commit the `.psd1`.

**Comment by joeltimothyoh** [comment]
> @joeltimothyoh if one is going to be publishing the module on PSGallery and .psd1 is mandatory, then one would have to commit the .psd1.

That's why both will be included in the `PSGallery` package, but only `.psm1` in the git repository. @leojonathanoh

**Comment by leojonathanoh** [comment]
@joeltimothyoh the problem with that is that the published module will contain `.psd1` and a `.psm1` containing `Export-ModuleMember`, you have to choose one or the other.

**Comment by leojonathanoh** [comment]
To generate a the module manifest with ExportedFunctions from `./src/Module/public/*` cmdlets, one can use [this line](https://github.com/theohbrothers/Get-DuplicateItem/blob/v1.1.3/build/definitions/modulemanifest/definition.ps1#L26) in the module manifest definition. Then no more using `Export-ModuleMember` anymore.

**Comment by joeltimothyoh** [comment]
both `.psd1` and `.psm1` are typically included in published packages with `Export-ModuleMember` included in `.psm1` files. Some examples being:

* https://www.powershellgallery.com/packages/newtonsoft.json/1.0.2.201
* https://www.powershellgallery.com/packages/powershell-yaml/0.4.2

I *don't* suppose including `Export-ModuleMember` in `.psm1` with `.psd1` in the same directory causes duplicate exports of specified functions.

**Comment by joeltimothyoh** [comment]
> To generate the module manifest with ExportedFunctions from ./src/Module/public/* cmdlets, one can use this line in the module manifest definition. Then no more using Export-ModuleMember anymore.

That's awful. Manifest definitions should be declarative. @leojonathanoh

**Comment by leojonathanoh** [comment]
@joeltimothyoh yes `.psd1` and `.psm1` are both published alongside one another.

> I don't suppose including Export-ModuleMember in .psm1 with .psd1 in the same directory causes duplicate exports of specified functions.

It does cause duplicates. See azp logs: https://dev.azure.com/theohbrothers/ItemLinkManagement/_build/results?buildId=314&view=logs&j=6faa9437-b161-58c7-e840-ecbc27faf593&t=84ddec43-f767-55cc-70a4-c66fc6a0b46e&l=115

**Comment by leojonathanoh** [comment]
> That's awful. Manifest definitions should be declarative. @leojonathanoh

True, but since the module manifest definition file is a `.ps1` script, then we can leverage it for dynamically determine what to export. Imagine if you added a new cmdlet, your module manifest will have to be manually updated with that new cmdlet. Thats why u use that line in https://github.com/theohbrothers/ItemLinkManagement/pull/2#issuecomment-890543026

**Comment by leojonathanoh** [comment]
@joeltimothyoh sometimes i wish the module manifest definition `.ps1` could simply be in `.src`, but currently our ` PSModulePublisher` still looks in `build/definitions/modulemanifest`

**Comment by joeltimothyoh** [comment]
> It does cause duplicates. See azp logs: https://dev.azure.com/theohbrothers/ItemLinkManagement/_build/results?buildId=314&view=logs&j=6faa9437-b161-58c7-e840-ecbc27faf593&t=84ddec43-f767-55cc-70a4-c66fc6a0b46e&l=115

If I'm not mistaken it's typical output of `Get-Module` to display each exported function twice in it's `.ExportedFunctions` property. If duplicate imports are occurring then it should be occurring based on the verbose output just earlier from where you referenced: https://dev.azure.com/theohbrothers/ItemLinkManagement/_build/results?buildId=314&view=logs&j=6faa9437-b161-58c7-e840-ecbc27faf593&t=84ddec43-f767-55cc-70a4-c66fc6a0b46e&l=67

I'm unsure why `two` of each exported function appears though. I've tried executing the build locally with `Export-ModuleMember` commented out in the `.psm1` file only to see `Add-Link` still appearing twice in it's `.ExportedFunctions` of `Get-Module`. @leojonathanoh

**Comment by leojonathanoh** [comment]
@joeltimothyoh im not sure perhaps it does show a duplicate even when `Export-ModuleMember` is removed from `.psm1`. But in general if one is going to be using `.psd1`, then `Export-ModuleMember` is actually a duplicate and might differ from the `.psd1` leading to differences in behavior depending on whether the module was imported via `.psd1` or `.psm1`. Hence it's best to stick to one way of importing which is the `.psd1`.

**Comment by joeltimothyoh** [comment]
> @joeltimothyoh sometimes i wish the module manifest definition .ps1 could simply be in ./src, but currently our PSModulePublisher still looks in build/definitions/modulemanifest

You can open an issue on `PSModulePublisher` specifying why `./src` is a preferred location for the manifest definition. @leojonathanoh

**Comment by joeltimothyoh** [comment]
> @joeltimothyoh im not sure perhaps it does show a duplicate even when Export-ModuleMember is removed from .psm1. But in general if one is going to be using .psd1, then Export-ModuleMember is actually a duplicate and might differ from the .psd1 leading to differences in behavior depending on whether the module was imported via .psd1 or .psm1. Hence it's best to stick to one way of importing which is the .psd1.

I'm really just following the convention of what' has to be included when publishing a module on PSGallery taking cues from the community and our past PS repositories. Things may have changed now: https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/publishing-packages/publishing-a-package @leojonathanoh

**Comment by leojonathanoh** [comment]
@joeltimothyoh powershell community doesn't really stick to best practices in general, a lot of ill discipline in publishing. I simply refer to the official docs about `Export-ModuleMember` https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/export-modulemember?view=powershell-7.1 and the best practices is to use a `.psd1` file: https://docs.microsoft.com/en-us/powershell/scripting/learn/ps101/10-script-modules?view=powershell-7.1#defining-public-and-private-functions

**Comment by joeltimothyoh** [comment]
> In particular in the best practices link, quote:
>  >  It's not necessary to use both Export-ModuleMember in the .PSM1 file and the FunctionsToExport section of the module manifest. One or the other is sufficient.

Makes sense. So basically it's like having just one source of truth for imports where they are performed with `.psd1 via `Import-Module -Path *.psd1`. This change however would require revision to `PSModulePublisher` since a committed `.psd1` is presently overridden in the build process.

**Comment by leojonathanoh** [comment]
> Makes sense. So basically it's like having just one source of truth for imports where they are performed with .psd1 via Import-Module -Path *.psd1

@joeltimothyoh yes single source of truth.

> This change however would require revision to PSModulePublisher since a committed .psd1 is presently overridden by the generated one in the build process. 

In our some of other projects using github workflows, the module manifest only built before publishing (i.e. on tagged releases). The perpetual module manifest is a dynamic manifest with version `0.0.0`. E.g. https://github.com/theohbrothers/Get-DuplicateItem/blob/v1.1.3/src/Get-DuplicateItem/Get-DuplicateItem.psd1

**Comment by leojonathanoh** [comment]
@joeltimothyoh in general, if using `.psd1`, everytime a new cmdlet is added, one needs to include a generated module manifest as part of a PR, by using a task like https://github.com/theohbrothers/Get-DuplicateItem/blob/v1.1.3/.vscode/tasks.json#L38-L46

**Pull request merged**
