### PR TITLE
Docs: Add documentation on project deprecation

### LINKED ISSUE #19: Deprecate project
Based on verbal recommendation by @leojonathanoh who discovered the equivalent of what this module does can be performed in merely several lines of PS code.

### PR DESCRIPTION
**Pull request by joeltimothyoh**
Closes #19

### CODE REVIEW

**Comment by leojonathanoh** [comment]
replaced `docs` label with the native `documentation` label because it is a duplicate

**Comment by leojonathanoh** [comment]
> I don't like the verbosity of the label. Labels are another thing to standardize on top of commit messages and MR titles except worse than the latter two I've never come across a convention for naming (and namespacing) them.

i agree, but since it's a native, i just use it because it's famiilar to everybody.

**Comment by joeltimothyoh** [comment]
Label colors are another thing to manage. If by using the native labels mean keeping even the native colors, even the colors will look confusing with our custom standardized ones. I've seen many projects delete the native labels, which can be performed for new repos by setting the defaults on an org level, an approach I prefer.

**Comment by leojonathanoh** [comment]
> Label colors are another thing to manage. If by using the native labels mean keeping even the native colors, even the colors will look confusing with our custom standardized ones. I've seen many projects delete the native labels, which can be performed for new repos by setting the defaults on an org level, an approach I prefer.

To me, labels ought to be managed by bots, based on keywords used in the conventional commit message, and the content of the commit message. These stuff like labels, label colors, etc ought to be configured on the group level, and synced across all of the group's repos. So to manage this by hand is kind of a mistake. But i guess an easy way to start off without using a bot, is to keep things as simple as possible and use native labels, and add a few other missing labels on the group level so that new repos automatically get them. (e.g. `refactor`, `style`, `feature`)

**Comment by joeltimothyoh** [comment]
lgtm

**Pull request merged**
