### PR TITLE
Refactor!: Rename function Add-Link to New-ItemLink

### LINKED ISSUE #3: Rename function to New-ItemLink
## Current 

Named `Add-Link`

## Expectation

Named `New-ItemLink`

## Discussion

To comply to powershell conventions and stay in line with inbuilt cmdlets, `New-ItemLink` sounds more intuitive than `Add-Link`. 

Also the fact that this module is a wrapper around `New-Item`, its name would be better resembling it.

### PR DESCRIPTION
**Pull request by joeltimothyoh**
Closes #3

### CODE REVIEW

**Comment by leojonathanoh** [comment]
@joeltimothyoh how about New-ItemLink, to make it clearer?

**Comment by leojonathanoh** [comment]
@joeltimothyoh update readme too

**Comment by joeltimothyoh** [comment]
> @joeltimothyoh how about New-ItemLink, to make it clearer?

For real? @leojonathanoh

**Comment by leojonathanoh** [comment]
@joeltimothyoh just throwing it out there, just a thought, what u think?

**Comment by joeltimothyoh** [comment]
> @joeltimothyoh just throwing it out there, just a thought, what u think?

I mean the module is named `ItemLinkManagement` and it's true there's an inconsistency. Either simplicity with just `New-Link` and naming the module `LinkManagement` or rename the function to `New-ItemLink`. @leojonathanoh

**Comment by leojonathanoh** [comment]
@joeltimothyoh it's really a `Item` which happens to be a `Link` (i.e. `-ItemType <any other than file or directory>`), so i'd say `ItemLink` is clearer and better.

**Comment by leojonathanoh** [comment]
@joeltimothyoh if you think that this module is never going to add more cmdlets, then the project might as well be `New-ItemLink`.

**Comment by joeltimothyoh** [comment]
> @joeltimothyoh it's really a Item which happens to be a Link (i.e. -ItemType <any other than file or directory>), so i'd say ItemLink is clearer and better.

Very well then.

**Comment by joeltimothyoh** [comment]
> @joeltimothyoh if you think that this module is never going to add more cmdlets, then the project might as well be New-ItemLink.

I don't think it's good practice to give modules names of functions.

**Comment by leojonathanoh** [comment]
To me, if a module is truly modular, and provides only one cmdlet, then it is much more streamlined to call the repo the same as the module and the very function name itself.

**Comment by joeltimothyoh** [comment]
> To me, if a module is truly modular, and provides only one cmdlet, then it is much more streamlined to call the repo the same as the module and the very function name itself.

I don't think it's worth risking limiting the project to a single function. @leojonathanoh

**Comment by leojonathanoh** [comment]
@joeltimothyoh yes so it really depends on what the module is providing.

**Comment by joeltimothyoh** [comment]
> @joeltimothyoh yes so it really depends on what the module is providing.

@leojonathanoh I think the module name is fine.

**Comment by joeltimothyoh** [comment]
Adding u as co-author @leojonathanoh

**Comment by leojonathanoh** [comment]
@joeltimothyoh ok

**Comment by joeltimothyoh** [comment]
lgtm

**Pull request merged**
